pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-2'
        ECR_REPOSITORY = 'hello-world-app'
        IMAGE_TAG = 'latest'
        AWS_ACCOUNT_ID = '891377228691'
        EKS_CLUSTER_NAME = 'tech-challenge-2-eks'
    }

    stages {
        stage('Checkout Source Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('app') {
                    sh 'docker build -t $ECR_REPOSITORY:$IMAGE_TAG .'
                }
            }
        }

        stage('Login to Amazon ECR') {
            steps {
                sh '''
                    aws ecr get-login-password --region $AWS_REGION |
                    docker login --username AWS --password-stdin \
                    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }

        stage('Tag and Push Docker Image') {
            steps {
                sh '''
                    docker tag $ECR_REPOSITORY:$IMAGE_TAG \
                    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

                    docker push \
                    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
                '''
            }
        }

        stage('Deploy to Amazon EKS with Helm') {
            steps {
                sh '''
                    aws eks update-kubeconfig \
                    --region $AWS_REGION \
                    --name $EKS_CLUSTER_NAME

                    helm upgrade --install hello-world ./helm/hello-world-chart \
                    --set image.repository=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY \
                    --set image.tag=$IMAGE_TAG
                '''
            }
        }
    }
}